#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# configuration variables, read from config file
ELECTRO_INSTANCE_ID="i-xxx"
HOST="prima"
PING_VPN="10.254.0.250"
AWS_PROFILE="default"
# optional
REMOTE_PATH="/home/ubuntu"
REMINDER_TIME="1750"

readonly config_path=~/.config/electro/
readonly config_file="config"
readonly script_url="https://raw.githubusercontent.com/primait/electro/master/electro"
readonly log_path="/tmp/electro-log/"

readonly ELECTRO_IGNORE="${PWD}/.electroignore"

rsync_options=""


test_electroignore() {
  if ! test -f "$ELECTRO_IGNORE"; then
      e_warning "File .electroignore not found in current path: $PWD"
      echo "Would you like to create one (type 1 for Yes, 2 for No)?"

      select yn in "Yes" "No"; do
        case $yn in
          Yes ) create_default_electroignore; break ;;
          No ) e_error "Can't proceed further without a .electroignore file in project path :("; exit;;
        esac
      done
  fi
}

create_default_electroignore() {
  e_warning "Writing default ${ELECTRO_IGNORE}"
  printf "# Common files and folders to exclude from sync \n" > $ELECTRO_IGNORE
  printf ".git/\n" >> $ELECTRO_IGNORE
  printf ".ssh/\n" >> $ELECTRO_IGNORE
  printf ".idea/\n" >> $ELECTRO_IGNORE
  printf ".vscode/\n" >> $ELECTRO_IGNORE
  printf ".electroignore\n" >> $ELECTRO_IGNORE
  printf ".DS_Store\n" >> $ELECTRO_IGNORE
  printf "\n# Project specific files and folders to exclude from sync \n" >> $ELECTRO_IGNORE
  printf "vendor/\n" >> $ELECTRO_IGNORE
  printf "node_modules/\n" >> $ELECTRO_IGNORE
  printf "web/assets/\n" >> $ELECTRO_IGNORE
  printf "web/compass/stylesheets/\n" >> $ELECTRO_IGNORE
  printf "web/bundles/\n" >> $ELECTRO_IGNORE
  printf "var/cache/\n" >> $ELECTRO_IGNORE
  printf "var/logs/\n" >> $ELECTRO_IGNORE
  printf "var/sessions/\n" >> $ELECTRO_IGNORE
  printf "elm-stuff/\n" >> $ELECTRO_IGNORE
  printf "_build/\n" >> $ELECTRO_IGNORE
  printf "deps/\n" >> $ELECTRO_IGNORE
  printf "web/js/\n" >> $ELECTRO_IGNORE
  printf "dist/\n" >> $ELECTRO_IGNORE
  printf "target/\n" >> $ELECTRO_IGNORE
  printf "target-docker/\n" >> $ELECTRO_IGNORE
  printf "public/assets/\n" >> $ELECTRO_IGNORE
  printf "public/compass/stylesheets/\n" >> $ELECTRO_IGNORE
  printf "public/bundles/\n" >> $ELECTRO_IGNORE
  printf "public/js/\n" >> $ELECTRO_IGNORE
}


readonly bold=$(tput bold)
readonly reset=$(tput sgr0)
readonly purple=$(tput setaf 171)
readonly red=$(tput setaf 1)
readonly green=$(tput setaf 76)
readonly tan=$(tput setaf 3)

e_header() {
    printf "\\n${bold}${purple}==========  %s  ==========${reset}\\n" "$@"
}

e_arrow() {
    printf "➜ %s\\n" "$@"
}

e_success() {
    printf "${green}✔ %s${reset}\\n" "$@"
}

e_error() {
    printf "${red}✖ %s${reset}\\n" "$@"
}

e_warning() {
    printf "${tan}➜ %s${reset}\\n" "$@"
}

notify() {
    osascript -e "display notification \"$*\" with title \"Electro Future\""
}

notification_for_mac() {
    local time
    local check_os
    time="$(date +'%H%M')"
    if [ "${time}" != "${REMINDER_TIME}" ] ; then
        sleep 50
        notification_for_mac "$*" &
    else
        check_os=$(uname -s)
        if [[ ${check_os} == "Darwin" ]]; then
            notify "$*"
        else
            printf "\\t === Sorry, but the nice notification doesn't work: %s === \\n" "$*"
        fi
    fi
}

check_vpn() {
    set +e
    if ! ping -c2 -q "${PING_VPN}" > /dev/null; then
        e_warning "You have not activated the VPN!"
        exit
    fi
    set -e
    true
}

get_project() {
    basename "$(pwd)"
}

kill_fswatch() {
    set +e
    fswatch_pid=$(cat "${log_path}$(get_project).pid")
    kill -9 "${fswatch_pid}"
    set -e
}

check_aws_sso() {
  set +e
  aws sts get-caller-identity; retVal=$?
  set -e
  if [ $retVal -ne 0 ]; then
     aws sso login
     sleep 2
  fi
}

start_services() {
    local check_os
    local instance_status
    local oldip
    local ip_key
    local instance_ip
    local k

    e_header "Verifying AWS SSO Login"

    check_aws_sso

    e_header "Starting instance: ${ELECTRO_INSTANCE_ID}"

    check_vpn

    check_os=$(uname -s)
    if [[ ${check_os} == "Darwin" ]]; then
        ssh-add -K ~/.ssh/id_rsa
    else
        ssh-add ~/.ssh/id_rsa
    fi

    instance_status=$(eval "${instance_describe_status_cmd}")
    if [[ "${instance_status}" == "stopped" ]]; then
        aws ec2 start-instances --instance-ids "${ELECTRO_INSTANCE_ID}" --profile=${AWS_PROFILE} > /dev/null
        for k in $(seq 1 5);
        do
            printf "."
            sleep 2
        done
        while [[ "${instance_status}" != "ok" ]]
        do
            instance_status=$(eval "${instance_status_cmd}")
            sleep 2
            printf "."
        done
    fi
    printf "\\n"

    e_success "Instance is ready"

    ip_key="PRIVATEIPADDRESS"
    #ip_key="ASSOCIATION"
    instance_ip=$(aws ec2 describe-instances --instance-ids ${ELECTRO_INSTANCE_ID} --profile=${AWS_PROFILE} --output text |grep ${ip_key} |head -1 |awk '{print $4}')

    e_success "Found IP ${instance_ip}"
    e_warning "Updating ~/.ssh/config and /etc/hosts"

    sed "/${HOST}/ s/.*/${instance_ip}	${HOST}/g" /etc/hosts > /tmp/hostsBK
    cat /tmp/hostsBK | sudo tee /etc/hosts 1> /dev/null
    rm /tmp/hostsBK
    #sed "/HostName/ s/.*/HostName ${INSTANCE_IP}/g" ~/.ssh/config > /tmp/sshconfig
    oldip=$(grep -w ${HOST} -A 1 ~/.ssh/config | awk '/HostName/ {print $2}')
    sed "s/${oldip}/${instance_ip}/g" ~/.ssh/config > /tmp/sshconfig
    cat /tmp/sshconfig > ~/.ssh/config
    rm /tmp/sshconfig

    if should_start_fswatch "$@"; then
        watch
    fi

    e_success "Now you can launch electro watch in your project folders"
    e_success "Remember: you can connect to the remote instance: ssh ${HOST}"

    notification_for_mac "Remember to switch off the remote instance!" &
}

should_start_fswatch() {
    local status=true
    for var in "$@"
    do
        if [ "${var}" == "--nowatch" ]; then
            status=false
            break
        fi
    done
    ${status}
}

stop_services() {
    local instance_status
    e_warning "Stopping instance"
    aws ec2 stop-instances --instance-ids ${ELECTRO_INSTANCE_ID} --profile=${AWS_PROFILE} > /dev/null
    sleep 5
    instance_status=$(eval "${instance_describe_status_cmd}")
    e_warning "Status: ${instance_status}"
    e_warning "Killing fswatch"
    killall_fswatch
}

check() {
    local instance_status
    local fswatch_pid
    local pid_file
    check_vpn
    instance_status=$(eval "${instance_describe_status_cmd}")
    if [[ "${instance_status}" != "running" ]]; then
        e_error "Instance state: ${instance_status}"
    else
        e_success "Instance state: OK"
    fi
    set +e
    pid_file="${log_path}$(get_project).pid"
    fswatch_pid=$(cat "${pid_file}" 2> /dev/null)
    if ps -p "${fswatch_pid}" &> /dev/null; then
        e_success "fswatch is running"
    else
        e_error "fswatch is not running"
    fi
    set -e

}

killall_fswatch() {
    set +e
    # local status=$?
    # if $(exit status); then
    if pgrep fswatch > /dev/null; then
        kill $(pgrep fswatch |awk '{print $1}')
    fi
    set -e
}

watch() {
    local logfile
    local pidfile
    local pid
    logfile="${log_path}$(get_project).log"
    pidfile="${log_path}$(get_project).pid"
    e_warning "Initializing fswatch: logging on ${logfile}"

    if eval "${fswatch_cmd} &" ; then
        #pid=$!
        pid=$(jobs -p)
        e_warning "PID: ${pid}"
        touch "${pidfile}"
        echo "${pid}" > "${pidfile}"
        e_success "Fswatch started"
    else
        e_error "Issues with fswatch"
    fi
}

stopwatch() {
    e_warning "Killing fswatch"
    kill_fswatch
    e_success "Fswatch killed"
}

logwatch() {
    local logfile
    logfile="${log_path}$(get_project).log"
    e_header "fswatch Log"
    tail -f "${logfile}"
}

update() {
    local scriptpath
    local scriptname
    local random_string
    scriptpath=$( cd "$(dirname "$0")" ; pwd -P )
    scriptname=$(basename "$0")
    e_header "Starting the script update"
    e_arrow "Saving in ${scriptpath}/${scriptname}"
    random_string=$(date +"%s")
    if curl -fsSL "${script_url}"?ran="${random_string}" -o "${scriptpath}/${scriptname}"; then
        e_success "Update succeeded!"
    else
        e_error "Issues with update"
    fi
}

usage() {
    e_header "electro usage:"
    e_arrow "start:       start the instance. with --nowatch flag doesn't start watch"
    e_arrow "stop:        stop fswatch and instance"
    e_arrow "check:       check the state of the instance and fswatch"
    e_arrow "watch:       start fswatch"
    e_arrow "stopwatch:   kill fswatch"
    e_arrow "log:         check fswatch log"
    e_arrow "update:      update this script"
    e_arrow "dc <cmd>:    run 'docker-compose <cmd>' on the remote instance"
    e_arrow "test-notification:   test notification at ${REMINDER_TIME}"
    printf "\\n"
    e_warning "Excluded paths:   ${rsync_options}"
    printf "\\n"
    e_warning "Remember to execute the commands in the project folder you want to work on!"
    printf "\\n"
}

doc_exec() {
    local parameters
    parameters="${@:2}"
    ssh "${HOST}" "cd ${REMOTE_PATH}/$(get_project);docker-compose ${parameters}"
}

build_rsync_options() {
  test_electroignore
  while read line; do
    if ! [[ $line == \#* ]] && [ -n "${line##+([[:space:]])}" ] ; then
      rsync_options="${rsync_options} --exclude=${line}"
    fi

  done < $ELECTRO_IGNORE
}

main() {
    build_rsync_options
    local cmd=${1:-}
    local logfile

    if [ ! -f "${config_path}${config_file}" ]; then
        e_warning "Creating configuration file: ${config_path}"
        mkdir -p ${config_path}
        touch ${config_path}${config_file}
        echo 'ELECTRO_INSTANCE_ID="i-xxx"
HOST="prima"
PING_VPN=""
AWS_PROFILE="default"
' > ${config_path}${config_file}

        e_warning "Remember to edit the file!"
        exit
    fi

    if [[ -z "$cmd" ]]; then
        usage
        exit 1
    fi

    if [ ! -d "${log_path}" ]; then
        mkdir "${log_path}"
    fi

    source "${config_path}${config_file}"

    logfile="${log_path}$(get_project).log"
    instance_status_cmd="aws ec2 describe-instance-status --instance-ids ${ELECTRO_INSTANCE_ID} --profile=${AWS_PROFILE} --output text |grep SYSTEMSTATUS | awk '{print \$2}'"
    fswatch_cmd="fswatch -o $(pwd) | xargs -n1 -I{} rsync -aruzvq --delete --log-file=${logfile} ${rsync_options} $(pwd) ${HOST}:${REMOTE_PATH}"
    instance_describe_status_cmd="aws ec2 describe-instances --instance-ids ${ELECTRO_INSTANCE_ID} --profile=${AWS_PROFILE} --output text |grep -w STATE |awk '{print \$3}'"
    if [[ $cmd == "start" ]]; then
        start_services "$@"
    elif [[ $cmd == "stop" ]]; then
        stop_services
    elif [[ $cmd == "check" ]]; then
        check
    elif [[ $cmd == "watch" ]]; then
        watch
    elif [[ $cmd == "stopwatch" ]]; then
        stopwatch
    elif [[ $cmd == "log" ]]; then
        logwatch
    elif [[ $cmd == "test-notification" ]]; then
        notify "Test notification" &
    elif [[ $cmd == "update" ]]; then
        update
    elif [[ $cmd == "dc" ]]; then
        doc_exec "$@"
    else
        usage
    fi
}

main "$@"
